// <auto-generated />
namespace Master.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class removedsymptomtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedsymptomtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201311121401514_removed symptom table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
